### ISSUE TITLE
Read server URLs from env vars

### ISSUE THREAD

**Issue by michielbdejong** [mozilla-services/syncclient#25]
For self-hosting, I want to set `TOKENSERVER_URL` and `FXA_SERVER_URL` to custom values. The easiest way would be through env vars, so that I can run syncto inside a Docker container, and the syncclient it relies on will react to env vars I pass to Docker at container startup. Would it make sense to do this with `os.environ.get`? If so, I can prepare a PR.

**Comment by Natim** [comment]
This URLs are syncto conf values that are already configurable from the ENV.

**Comment by michielbdejong** [comment]
Ah, I found https://github.com/mozilla-services/syncto/blob/master/syncto/__init__.py#L28 - so the name of the env var would be 'token_server_url' in lower-case? And I guess the FxA server URL is not used, since a request to syncto already contains a browserid assertion, right?

**Comment by almet** [comment]
It should actually be `SYNCTO_TOKEN_SERVER_URL`, [from the code of cliquet](https://github.com/mozilla-services/cliquet/blob/13089620ca257489ed5bb85e90f494799cf37bae/cliquet/initialization.py#L487).

**Comment by michielbdejong** [comment]
That worked, thanks!

**Comment by Natim** [comment]
Great :+1:
